// Generated by gencpp from file pwm_driver/SetDutyCycleResponse.msg
// DO NOT EDIT!


#ifndef PWM_DRIVER_MESSAGE_SETDUTYCYCLERESPONSE_H
#define PWM_DRIVER_MESSAGE_SETDUTYCYCLERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pwm_driver
{
template <class ContainerAllocator>
struct SetDutyCycleResponse_
{
  typedef SetDutyCycleResponse_<ContainerAllocator> Type;

  SetDutyCycleResponse_()
    {
    }
  SetDutyCycleResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }






  typedef boost::shared_ptr< ::pwm_driver::SetDutyCycleResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pwm_driver::SetDutyCycleResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetDutyCycleResponse_

typedef ::pwm_driver::SetDutyCycleResponse_<std::allocator<void> > SetDutyCycleResponse;

typedef boost::shared_ptr< ::pwm_driver::SetDutyCycleResponse > SetDutyCycleResponsePtr;
typedef boost::shared_ptr< ::pwm_driver::SetDutyCycleResponse const> SetDutyCycleResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pwm_driver::SetDutyCycleResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pwm_driver::SetDutyCycleResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pwm_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pwm_driver::SetDutyCycleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pwm_driver::SetDutyCycleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pwm_driver::SetDutyCycleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pwm_driver::SetDutyCycleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pwm_driver::SetDutyCycleResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pwm_driver::SetDutyCycleResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pwm_driver::SetDutyCycleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::pwm_driver::SetDutyCycleResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::pwm_driver::SetDutyCycleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pwm_driver/SetDutyCycleResponse";
  }

  static const char* value(const ::pwm_driver::SetDutyCycleResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pwm_driver::SetDutyCycleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::pwm_driver::SetDutyCycleResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pwm_driver::SetDutyCycleResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetDutyCycleResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pwm_driver::SetDutyCycleResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::pwm_driver::SetDutyCycleResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // PWM_DRIVER_MESSAGE_SETDUTYCYCLERESPONSE_H
