// Generated by gencpp from file pwm_driver/SetDutyCycleRequest.msg
// DO NOT EDIT!


#ifndef PWM_DRIVER_MESSAGE_SETDUTYCYCLEREQUEST_H
#define PWM_DRIVER_MESSAGE_SETDUTYCYCLEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pwm_driver
{
template <class ContainerAllocator>
struct SetDutyCycleRequest_
{
  typedef SetDutyCycleRequest_<ContainerAllocator> Type;

  SetDutyCycleRequest_()
    : channel(0)
    , value(0)  {
    }
  SetDutyCycleRequest_(const ContainerAllocator& _alloc)
    : channel(0)
    , value(0)  {
  (void)_alloc;
    }



   typedef int8_t _channel_type;
  _channel_type channel;

   typedef int8_t _value_type;
  _value_type value;




  typedef boost::shared_ptr< ::pwm_driver::SetDutyCycleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pwm_driver::SetDutyCycleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetDutyCycleRequest_

typedef ::pwm_driver::SetDutyCycleRequest_<std::allocator<void> > SetDutyCycleRequest;

typedef boost::shared_ptr< ::pwm_driver::SetDutyCycleRequest > SetDutyCycleRequestPtr;
typedef boost::shared_ptr< ::pwm_driver::SetDutyCycleRequest const> SetDutyCycleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pwm_driver::SetDutyCycleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pwm_driver::SetDutyCycleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pwm_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pwm_driver::SetDutyCycleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pwm_driver::SetDutyCycleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pwm_driver::SetDutyCycleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pwm_driver::SetDutyCycleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pwm_driver::SetDutyCycleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pwm_driver::SetDutyCycleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pwm_driver::SetDutyCycleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1ae5219cd7525faee248995c37ceecae";
  }

  static const char* value(const ::pwm_driver::SetDutyCycleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1ae5219cd7525faeULL;
  static const uint64_t static_value2 = 0xe248995c37ceecaeULL;
};

template<class ContainerAllocator>
struct DataType< ::pwm_driver::SetDutyCycleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pwm_driver/SetDutyCycleRequest";
  }

  static const char* value(const ::pwm_driver::SetDutyCycleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pwm_driver::SetDutyCycleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "byte channel\n\
byte value\n\
";
  }

  static const char* value(const ::pwm_driver::SetDutyCycleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pwm_driver::SetDutyCycleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.channel);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetDutyCycleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pwm_driver::SetDutyCycleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pwm_driver::SetDutyCycleRequest_<ContainerAllocator>& v)
  {
    s << indent << "channel: ";
    Printer<int8_t>::stream(s, indent + "  ", v.channel);
    s << indent << "value: ";
    Printer<int8_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PWM_DRIVER_MESSAGE_SETDUTYCYCLEREQUEST_H
