// Generated by gencpp from file pwm_driver/SetDutyCycle.msg
// DO NOT EDIT!


#ifndef PWM_DRIVER_MESSAGE_SETDUTYCYCLE_H
#define PWM_DRIVER_MESSAGE_SETDUTYCYCLE_H

#include <ros/service_traits.h>


#include <pwm_driver/SetDutyCycleRequest.h>
#include <pwm_driver/SetDutyCycleResponse.h>


namespace pwm_driver
{

struct SetDutyCycle
{

typedef SetDutyCycleRequest Request;
typedef SetDutyCycleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetDutyCycle
} // namespace pwm_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pwm_driver::SetDutyCycle > {
  static const char* value()
  {
    return "1ae5219cd7525faee248995c37ceecae";
  }

  static const char* value(const ::pwm_driver::SetDutyCycle&) { return value(); }
};

template<>
struct DataType< ::pwm_driver::SetDutyCycle > {
  static const char* value()
  {
    return "pwm_driver/SetDutyCycle";
  }

  static const char* value(const ::pwm_driver::SetDutyCycle&) { return value(); }
};


// service_traits::MD5Sum< ::pwm_driver::SetDutyCycleRequest> should match 
// service_traits::MD5Sum< ::pwm_driver::SetDutyCycle > 
template<>
struct MD5Sum< ::pwm_driver::SetDutyCycleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pwm_driver::SetDutyCycle >::value();
  }
  static const char* value(const ::pwm_driver::SetDutyCycleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pwm_driver::SetDutyCycleRequest> should match 
// service_traits::DataType< ::pwm_driver::SetDutyCycle > 
template<>
struct DataType< ::pwm_driver::SetDutyCycleRequest>
{
  static const char* value()
  {
    return DataType< ::pwm_driver::SetDutyCycle >::value();
  }
  static const char* value(const ::pwm_driver::SetDutyCycleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pwm_driver::SetDutyCycleResponse> should match 
// service_traits::MD5Sum< ::pwm_driver::SetDutyCycle > 
template<>
struct MD5Sum< ::pwm_driver::SetDutyCycleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pwm_driver::SetDutyCycle >::value();
  }
  static const char* value(const ::pwm_driver::SetDutyCycleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pwm_driver::SetDutyCycleResponse> should match 
// service_traits::DataType< ::pwm_driver::SetDutyCycle > 
template<>
struct DataType< ::pwm_driver::SetDutyCycleResponse>
{
  static const char* value()
  {
    return DataType< ::pwm_driver::SetDutyCycle >::value();
  }
  static const char* value(const ::pwm_driver::SetDutyCycleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PWM_DRIVER_MESSAGE_SETDUTYCYCLE_H
