#~ Topics for publishing/subscribing
occupancy_grid_publish_topic : /map
robot_trajectory_publish_topic : /robot_trajectory
trajectory_publisher_frame_id : map
laser_subscriber_topic : /scan_in
pose_publish_topic: /slam_pose
publish_tf: false

#~ Tf frames
base_footprint_frame : base_footprint
base_frame : base_link
map_frame : map

#~ SLAM parameters
hill_climbing_disparity : 50
slam_container_size : 500
slam_occupancy_grid_dimentionality : 0.01
map_update_density : 40
map_update_obstacle_density : 3.0
scan_density_lower_boundary : 0.3
max_hill_climbing_iterations : 40000
desired_number_of_picked_rays : 40

#~ Publishing frequencies (Hz)
occupancy_grid_map_freq : 1.0
robot_pose_tf_freq : 15.0
trajectory_freq : 1.0

#~ Robot parameters
robot_width : 0.1
robot_length : 0.1
