// Generated by gencpp from file pin_test/LedState.msg
// DO NOT EDIT!


#ifndef PIN_TEST_MESSAGE_LEDSTATE_H
#define PIN_TEST_MESSAGE_LEDSTATE_H

#include <ros/service_traits.h>


#include <pin_test/LedStateRequest.h>
#include <pin_test/LedStateResponse.h>


namespace pin_test
{

struct LedState
{

typedef LedStateRequest Request;
typedef LedStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LedState
} // namespace pin_test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pin_test::LedState > {
  static const char* value()
  {
    return "b06b243ca7fb95b6d7d5a6ac2b1f7c85";
  }

  static const char* value(const ::pin_test::LedState&) { return value(); }
};

template<>
struct DataType< ::pin_test::LedState > {
  static const char* value()
  {
    return "pin_test/LedState";
  }

  static const char* value(const ::pin_test::LedState&) { return value(); }
};


// service_traits::MD5Sum< ::pin_test::LedStateRequest> should match 
// service_traits::MD5Sum< ::pin_test::LedState > 
template<>
struct MD5Sum< ::pin_test::LedStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pin_test::LedState >::value();
  }
  static const char* value(const ::pin_test::LedStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pin_test::LedStateRequest> should match 
// service_traits::DataType< ::pin_test::LedState > 
template<>
struct DataType< ::pin_test::LedStateRequest>
{
  static const char* value()
  {
    return DataType< ::pin_test::LedState >::value();
  }
  static const char* value(const ::pin_test::LedStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pin_test::LedStateResponse> should match 
// service_traits::MD5Sum< ::pin_test::LedState > 
template<>
struct MD5Sum< ::pin_test::LedStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pin_test::LedState >::value();
  }
  static const char* value(const ::pin_test::LedStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pin_test::LedStateResponse> should match 
// service_traits::DataType< ::pin_test::LedState > 
template<>
struct DataType< ::pin_test::LedStateResponse>
{
  static const char* value()
  {
    return DataType< ::pin_test::LedState >::value();
  }
  static const char* value(const ::pin_test::LedStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PIN_TEST_MESSAGE_LEDSTATE_H
