// Generated by gencpp from file pin_test/LedStateResponse.msg
// DO NOT EDIT!


#ifndef PIN_TEST_MESSAGE_LEDSTATERESPONSE_H
#define PIN_TEST_MESSAGE_LEDSTATERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pin_test
{
template <class ContainerAllocator>
struct LedStateResponse_
{
  typedef LedStateResponse_<ContainerAllocator> Type;

  LedStateResponse_()
    {
    }
  LedStateResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }






  typedef boost::shared_ptr< ::pin_test::LedStateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pin_test::LedStateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct LedStateResponse_

typedef ::pin_test::LedStateResponse_<std::allocator<void> > LedStateResponse;

typedef boost::shared_ptr< ::pin_test::LedStateResponse > LedStateResponsePtr;
typedef boost::shared_ptr< ::pin_test::LedStateResponse const> LedStateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pin_test::LedStateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pin_test::LedStateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pin_test

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pin_test::LedStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pin_test::LedStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pin_test::LedStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pin_test::LedStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pin_test::LedStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pin_test::LedStateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pin_test::LedStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::pin_test::LedStateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::pin_test::LedStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pin_test/LedStateResponse";
  }

  static const char* value(const ::pin_test::LedStateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pin_test::LedStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::pin_test::LedStateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pin_test::LedStateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LedStateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pin_test::LedStateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::pin_test::LedStateResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // PIN_TEST_MESSAGE_LEDSTATERESPONSE_H
