// Generated by gencpp from file pin_test/LedStateRequest.msg
// DO NOT EDIT!


#ifndef PIN_TEST_MESSAGE_LEDSTATEREQUEST_H
#define PIN_TEST_MESSAGE_LEDSTATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pin_test
{
template <class ContainerAllocator>
struct LedStateRequest_
{
  typedef LedStateRequest_<ContainerAllocator> Type;

  LedStateRequest_()
    : open(false)  {
    }
  LedStateRequest_(const ContainerAllocator& _alloc)
    : open(false)  {
  (void)_alloc;
    }



   typedef uint8_t _open_type;
  _open_type open;




  typedef boost::shared_ptr< ::pin_test::LedStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pin_test::LedStateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LedStateRequest_

typedef ::pin_test::LedStateRequest_<std::allocator<void> > LedStateRequest;

typedef boost::shared_ptr< ::pin_test::LedStateRequest > LedStateRequestPtr;
typedef boost::shared_ptr< ::pin_test::LedStateRequest const> LedStateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pin_test::LedStateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pin_test::LedStateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pin_test

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pin_test::LedStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pin_test::LedStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pin_test::LedStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pin_test::LedStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pin_test::LedStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pin_test::LedStateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pin_test::LedStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b06b243ca7fb95b6d7d5a6ac2b1f7c85";
  }

  static const char* value(const ::pin_test::LedStateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb06b243ca7fb95b6ULL;
  static const uint64_t static_value2 = 0xd7d5a6ac2b1f7c85ULL;
};

template<class ContainerAllocator>
struct DataType< ::pin_test::LedStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pin_test/LedStateRequest";
  }

  static const char* value(const ::pin_test::LedStateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pin_test::LedStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool open\n\
";
  }

  static const char* value(const ::pin_test::LedStateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pin_test::LedStateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.open);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LedStateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pin_test::LedStateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pin_test::LedStateRequest_<ContainerAllocator>& v)
  {
    s << indent << "open: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.open);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PIN_TEST_MESSAGE_LEDSTATEREQUEST_H
